{{- range .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .serviceAccount.name }}
            namespace: {{ $.Release.Namespace }}
{{- end }}